{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 32,
   "id": "cbadcdfa-817e-478a-983d-fe6c5f061dab",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import sympy as sp\n",
    "gbar=9.81\n",
    "L=1\n",
    "Δ = 0.01\n",
    "θd = np.pi/6\n",
    "θ0 = 0-θd\n",
    "ω0 = 0\n",
    "tf=20\n",
    "NN=tf / Δ\n",
    "α = 0.005\n",
    "β = 1\n",
    "γ = 0.9\n",
    "R = .05\n",
    "kωe = 0.2\n",
    "q = [[1, 0], [0, 1]]\n",
    "σν = 0.1\n",
    "kθ = 2*gbar/L\n",
    "kω = 2\n",
    "\n",
    "def phi_basis(X1, X2):\n",
    "    result = np.array([[X1, X2, X1*X1, X1*X2, X2*X2]]).T\n",
    "    \n",
    "    return result\n",
    "\n",
    "def D_phi_basis(X1, X2):\n",
    "    result = np.array([[1, 0, 2*X1, X2, 0],\n",
    "                       [0, 1, 0, X1, 2*X2]]).T\n",
    "    return (result)\n",
    "    \n",
    "NL = 5\n",
    "\n",
    "W0 = np.array([[np.random.normal(0, 0.1),\n",
    "                np.random.normal(0, 0.1),\n",
    "                np.random.normal(0, 0.1),\n",
    "                np.random.normal(0, 0.1),\n",
    "                np.random.normal(0, 0.1)]]).T\n",
    "\n",
    "U0 = np.array([[np.random.normal(0, 0.1),\n",
    "                np.random.normal(0, 0.1),\n",
    "                np.random.normal(0, 0.1),\n",
    "                np.random.normal(0, 0.1),\n",
    "                np.random.normal(0, 0.1)]]).T\n",
    "def f(X1, X2):\n",
    "    result_part1 = np.array([[X1],[X2]])\n",
    "    \n",
    "    result_part2 = np.array([[X2], [((gbar/L)*(np.sin(θd)-np.sin(θd+X1))) - kωe*(X2)]])\n",
    "    \n",
    "    return result_part1 + Δ*result_part2\n",
    "\n",
    "def g(u):\n",
    "    result = u*np.array([0,Δ])\n",
    "    return result\n",
    "\n",
    "def r(X1, X2, u):\n",
    "    X = np.array([[X1],\n",
    "                  [X2]])\n",
    "    result = X.T @ q @ X + R*u*u\n",
    "    return float(result)\n",
    "\n",
    "X_list = []\n",
    "U_list = []\n",
    "W_list = [W0]\n",
    "u_list = []\n",
    "u_k=1\n",
    "W_k = W0\n",
    "U_k = U0\n",
    "kt = 0\n",
    "tΔ = [0]\n",
    "uj = (-γ / 2)* (1/R) * g(u_k) @ D_phi_basis(θ0, ω0).T @ W0 \n",
    "Wji = W0\n",
    "\n",
    "tc = []\n",
    "θ0_list, ω0_list = [],[]\n",
    "\n",
    "w1_list, w2_list, w3_list, w4_list, w5_list = [],[],[],[],[]\n",
    "\n",
    "\n",
    "for k in range(int(NN)):\n",
    "    θ0_list.append(θ0)\n",
    "    ω0_list.append(ω0)\n",
    "    X_k = f(θ0, ω0) + g(uj)\n",
    "    X_list.append(X_k)\n",
    "    θ0, ω0  = X_k[0][0], X_k[1][0]\n",
    "    \n",
    "    phi = phi_basis(θ0,ω0)\n",
    "    \n",
    "    r_k = r(θ0, ω0, u_k) + γ*float(phi_basis(θ0, ω0).T @ Wji)\n",
    "    \n",
    "    ecount = 1\n",
    "    Wjim = W_list[-1]\n",
    "    Wji = Wji - α*phi_basis(θ0, ω0)*(float(phi_basis(θ0, ω0).T @ Wji) - r_k)\n",
    "    \n",
    "    while ecount < 100 and float((Wji - Wjim).T @ (Wji - Wjim)) > 10**-5:\n",
    "        Wjim = W_list[-1]\n",
    "        #gradient descent\n",
    "        Wji = Wji - α*phi_basis(θ0, ω0)*(float(phi_basis(θ0, ω0).T @ Wji) - r_k)\n",
    "        ecount+=1\n",
    "        \n",
    "        \n",
    "    W_list.append(Wji)\n",
    "    \n",
    "    w1_list.append(Wji[0][0])\n",
    "    w2_list.append(Wji[1][0])\n",
    "    w3_list.append(Wji[2][0])\n",
    "    w4_list.append(Wji[3][0])\n",
    "    w5_list.append(Wji[4][0])\n",
    "    \n",
    "    #need to update u with the weights from W\n",
    "    #policy improvement - update u_j\n",
    "    uj = -(γ/2)*(R**-1)*float(g(uj).T @ D_phi_basis(θ0 , ω0).T @ W_list[-1])\n",
    "    u_list.append(uj)\n",
    "    tc.append(k)\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "75a4103d-da61-47e1-a9fd-a56ddead17b0",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ca31139c-241c-4d44-ad6a-8f951a4a28c5",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
